### ISSUE TITLE
阅读全文/ read more

### ISSUE THREAD

**Issue by sam2099** [wuchong/jacman#100]
请问 首页 上 每个 blog 的 “阅读全文/ read more ” 如何配置才能显示？

在themes/jacman/_config.yml下，找到index索引下的expand: true 的话， 首页就显示了blog全文。

我的博客地址：http://giveme5.top/

**Comment by wuchong** [comment]
在文章中需要截断的地方添加 

```html
<!--more-->
```

**Comment by sam2099** [comment]
啊哈， 3q
