### ISSUE TITLE
Wrong display at IE 11, Win7

### ISSUE THREAD

**Issue by st2py** [wuchong/jacman#102]
Hi wuchong, 

I plan to set up my blog by using hexo and jacman.
But it seems display incorrect with IE 11, Win7 OS.
Please help me to check the issue.
Thx a lot.

**Comment by st2py** [comment]
![default](https://cloud.githubusercontent.com/assets/8953610/11421455/0363feae-9470-11e5-9335-e84bbe33ca06.png)

**Comment by st2py** [comment]
any comment?

**Comment by wuchong** [comment]
Sorry for late response , I will fix it in few days

**Comment by wuchong** [comment]
fixed
