### ISSUE TITLE
为什么在自己的网站上有别人网站上的评论？

### ISSUE THREAD

**Issue by krzer** [wuchong/jacman#103]
![2015-12-02 21 01 00](https://cloud.githubusercontent.com/assets/15955156/11531452/db32175a-9937-11e5-89a9-74825ece321d.png)
这些评论并不是我的，但是却显示在我的网站上，求解，谢谢！

**Comment by labrick** [comment]
这个应该和你的评论系统（多说？）有关系；多说偶尔会有垃圾评论存在；

**Comment by krzer** [comment]
对，没错，确实是多说的问题，我一开始还以为是自带的分享的问题……
