### ISSUE TITLE
请问下使用该主题后，本地使用hexo s查看是正常的。Push到Github上就是一片空白呢？

### ISSUE THREAD

**Issue by yuxiangq** [wuchong/jacman#104]

**Comment by wuchong** [comment]
请提供下你的 github链接和 博客链接

**Comment by yuxiangq** [comment]
我收到github的邮件提示 「The submodule `themes/jacman` was not properly initialized with a `.gitmodules` file」

**Comment by yuxiangq** [comment]
嗯，是因为还有仓库的原因
