### ISSUE TITLE
图片位置问题

### ISSUE THREAD

**Issue by snowdream** [wuchong/jacman#115]
我的博客位置设置在http://snowdream.github.io//blog/下，图片的位置在http://snowdream.github.io//blog/images下，但是hexo自动索引到http://snowdream.github.io//images下，因此出现找不到图片的情况。请问如何解决？是否需要添加类似 {{BASE_PATH}}之类的全局变量？

**Comment by snowdream** [comment]
博客地址：http://snowdream.github.io/blog/about/
图片地址：http://snowdream.github.io/blog/images/IMG_6092.JPG

**Comment by wuchong** [comment]
根目录的配置文件中设置 `root: /blog`

**Comment by snowdream** [comment]
已经解决，感谢。
