### ISSUE TITLE
如何在右边栏显示分类？

### ISSUE THREAD

**Issue by dayupcui** [wuchong/jacman#119]
我想在右边栏添加分类，如何做呢？

**Comment by hsihohuang** [comment]
在jacman的_config.yml档案里面设定
widgets底下要有category，设定只要在前面加 - 即可，如下
```
widgets: 
- github-card
- category
- tag
- links
- douban
- rss
- weibo
```

**Comment by dayupcui** [comment]
@hsihohuang 我已经在_config.yml中添加了category，为什么还显示不出来，是需要再设置什么嘛，如下图：
[345.pdf](https://github.com/wuchong/jacman/files/163302/345.pdf)

我需要实现的效果如下图：
![123](https://cloud.githubusercontent.com/assets/17631451/13604168/8101b6aa-e57c-11e5-82b9-7541c8e4dd24.png)

**Comment by dayupcui** [comment]
@hsihohuang 我已经在_config.yml中添加了category，为什么还显示不出来，是需要再设置什么嘛，如下图：
![567](https://cloud.githubusercontent.com/assets/17631451/13604236/ca50f730-e57c-11e5-9c05-ed098f4d3eb3.png)

我需要实现的效果如下图：
![789](https://cloud.githubusercontent.com/assets/17631451/13604515/00dd5536-e57e-11e5-9ef3-0eefd3debfc4.jpg)

**Comment by hsihohuang** [comment]
请问您有在hexo博客资料夹底下的`source`资料夹中新增`categories`资料夹吗？
如下圖：

<img width="679" alt="myblog_source_categories" src="https://cloud.githubusercontent.com/assets/15816777/13604906/15845d20-e580-11e5-93f5-f3401068a552.png">

如果没有的话，需要先新增，您可以在hexo博客资料夹底下使用`hexo new page categories` 指令新增，它就会在`source`资料夹底下自动产生了

之后您只要在所新增的文章当中，最上面加入类别的设定即可，像这样
```
---
title: 文章标题
date: 2016-03-08 23:01:00
tags:
- 标签名称
categories:
- 分类名称
---
```

**Comment by dayupcui** [comment]
@hsihohuang 谢谢，搞定了！
