### ISSUE TITLE
自定义widget问题

### ISSUE THREAD

**Issue by dayupcui** [wuchong/jacman#120]
我想在右侧边栏添加一个小工具，title显示“技术资讯”，就类似于分类、友情链接等等这种，我在jacman->layout->_widget目录下创建了一个news.ejs文件，如下图代码：

    <div class=“newslist">
      <p class="asidetitle"><%= __(‘news') %></p>
        <ul>
            <% for (var i in theme.news){ %>
              <li>
                <% if(theme.news[i].indexOf(",") > 0) { %>
            	    <a href="<%- theme.news[i].split(",")[0] %>" target="_blank" title="<%-     theme.news[i].split(",")[1] %>"><%= i %></a>
                <% }else{ %>
                	<a href="<%- theme.news[i] %>" target="_blank" title="<%= i %>"><%= i %></a>
                <% } %>
              </li>
        <% } %>
    </ul>
</div> `

我想知道<%= __(‘news') %>里面的含义，因为我调用hexo g生成时，报出错误找不到 
`WARN  Partial ../_widget/news does not exist. (in _partial/sidebar.ejs)`

**Comment by wuchong** [comment]
`<%= __(‘news') %>`  是多语言中的 news 代表的字符。 也就是  zh_cn.yaml 、 en.yaml 中得要有这个字段。

另外你这里面有个中文的引号，这个应该是有问题的

**Comment by CharlesHappy** [comment]
@wuchong 找到问题了，谢谢，就是中文引号的问题
