### ISSUE TITLE
可以另起炉灶建一个文件夹吗？

### ISSUE THREAD

**Issue by JasonSi** [wuchong/jacman#124]
_posts 文件夹下会被编译到类似 2016/3/22/title.html 
我新建了一个page 叫about，文件夹下的index.md 写了自我简介

然而我现在想再加一个page 比如叫list  里面再创建一个文件夹posts，里面有很多很多文章，
访问 /list/index.html的 时候就像  访问网站主页一样 把list/posts里的文章列出来？ 

没有看懂partial的是怎么依赖的...
可以实现吗 或者提供思路吗？

**Comment by wuchong** [comment]
据我了解好像不支持这个功能呢。

**Comment by JasonSi** [comment]
好的吧～以后有闲心换wordpress折腾hhh～ 谢啦
