### ISSUE TITLE
请教关于目录前序号

### ISSUE THREAD

**Issue by QAQMiao** [wuchong/jacman#126]
![image](https://cloud.githubusercontent.com/assets/8213657/14410267/ca9896e4-ff5d-11e5-9a5a-39466aedea25.png)

<%- toc(post.content, {list_number: true}) %>
我通过这句话给文章加上了目录，但是出现了两重序号，我想要把圈起来的那个序号去掉，请问应该如何处理呢？

**Comment by wuchong** [comment]
list_number: false
