### ISSUE TITLE
为什么会创建重复分类？

### ISSUE THREAD

**Issue by whatbeg** [wuchong/jacman#129]
我的“机器学习”分类有两篇文章，其中一篇我分类到两个：categories: [Python,机器学习]，另外一篇的分类为：categories: 机器学习， 这时候主页的分类里面就会有两个“机器学习”分类，显示各一篇文章，显然这不是理想的效果，请问该如何解决呢？

**Comment by wuchong** [comment]
hexo 不支持多分类。 categories: [Python,机器学习] 这种写法是多级分类。也就是 “机器学习” 是 “Python” 下的子分类。

建议 categories 只填写一个分类。  tags 中填写多个
