### ISSUE TITLE
首页中文摘要显示乱码

### ISSUE THREAD

**Issue by wayne798** [wuchong/jacman#133]
Mac系统，hexo3.2，md文件是utf-8的，但是发表文章后，首页显示，中文标题是正常的，但是内容摘要却是乱码：&#x54c8;&#x54c8
好像是被转意了啊，但是点进去，文章是可以正常显示的。
请问这是什么情况呢？

**Comment by wuchong** [comment]
摘要写在 description 中的 ？

**Comment by wayne798** [comment]
现在的配置是: expand: false 
文件test.md:
---
 title: test
date: 2016-05-11 15:00:23
categories:
- iOS
tags:
 ---
哈哈哈哈哈,测试

如果expand：ture，并且加上这样是没问题的。

**Comment by wayne798** [comment]
现在的配置是
`expand: false`
文件test.md
`--`
`title: test`
` date: 2016-05-11 15:00:23`
 `categories:`
`- iOS`
` tags:`
`---`
`哈哈哈哈哈,测试`

**Comment by wayne798** [comment]
自己使用的不对，没有把描述放到description里面，多谢提醒。
