### ISSUE TITLE
建议增加支付宝，微信打赏功能

### ISSUE THREAD

**Issue by snowdream** [wuchong/jacman#137]
类似这样：
1.  https://github.com/xirong/hexo-theme-next/wiki/%E5%A2%9E%E5%8A%A0%E5%8D%9A%E5%AE%A2%E6%89%93%E8%B5%8F%E5%8A%9F%E8%83%BD
1. http://www.ixirong.com/2015/05/24/hexo-blog-donate/

**Comment by snowdream** [comment]
@wuchong

**Comment by luoxugeng** [comment]
[根据这个链接](http://whatbeg.com/2016/05/18/hexo-donate.html) 解决问题

**Comment by snowdream** [comment]
@luoxugeng 感谢分享。🙏
