### ISSUE TITLE
文章的目录过长会遮挡代码块，代码块过长会跑出屏幕。

### ISSUE THREAD

**Issue by cuitengtai** [wuchong/jacman#151]

**Comment by luoxugeng** [comment]
同意,也遇到这个问题.目录大一点, 侧边栏干脆只显示一半

**Comment by cuitengtai** [comment]
这个问题我解决了，在使用MarkDown语法写代码块时使用下面这种方式就可以避免：

```
Your Code
```
我之前出问题的原因是书写代码使用了Tab键缩进方式，希望能够帮到你。
