### ISSUE TITLE
github card 区域直接将html代码显示出来了

### ISSUE THREAD

**Issue by zachaxy** [wuchong/jacman#165]
昨天发现github card 区域直接显示出了html代码,pull了最新的主题,有时候访问是好的,但大部分时间还是显示html代码.我的博客https://zachaxy.github.io/

**Comment by lazywhite** [comment]
一样的问题

**Comment by peierlong** [comment]
The same problem

**Comment by cealiu** [comment]
替换 layout/_widget/github-card.ejs文件中的src为
lab.lepture.com/github-cards/widget.js
估计说最近这个cdn中的js代码有问题，不改估计等段时间会好。
