### ISSUE TITLE
怎么集成 Gitment 评论系统？

### ISSUE THREAD

**Issue by pengcheng789** [wuchong/jacman#176]
你好！😄请问在 Jacman 主题下怎样才能使用 [Gitment](https://github.com/imsun/gitment) 这个评论系统？

**Comment by bicyclering** [comment]
@wuchong  
hexo 支持了 gitment 评论系统
# Gitment
 # Introduction: https://imsun.net/posts/gitment-introduction/
gitment:
  enable: true
  githubID: zonghongyan
  repo: zonghongyan.github.io
  ClientID: ------
  ClientSecret: ------
  lazy: false

请问一下 jacman 如何 配置 gitment

**Comment by bicyclering** [comment]
@pengcheng789  解决了吗

**Comment by pengcheng789** [comment]
抱歉抱歉，现在才看到信息，貌似之前邮箱设置出了一点问题。

@bicyclering 谢谢您的答复！😊
