### ISSUE TITLE
修改网站个人介绍后generate出错

### ISSUE THREAD

**Issue by tufu9441** [wuchong/jacman#22]
我只要在主题目录的_config.yml中一修改作者介绍的那两句话，“Hello, I am Larry Page in Google.”和下面的那一行，在执行hexo generate的时候就会出错，提示如下：
[error] { name: 'HexoError',
  reason: 'deficient indentation',
  mark: 
   { name: null,
     buffer: '##### Menu\nmenu:\n  Home: /\n  Archives: /archives\n  About: /about\n  History: /history\n## you can create `tags` and `categories` folders in `../source`.\n## And create a `index.md` file in each of them.\n## set `front-matter`as\n## layout: tags (or categories)\n## title: tags (or categories)\n## ---\n\n#### Widgets\nwidgets: \n- category\n- tag\n- links\n- rss\n## provide seven widgets:category,tag,rss,archive,tagcloud,links,weibo\n\n\n#### RSS \nrss: /atom.xml ## RSS address.\n\n#### Image\nimglogo:\n  enable: true             ## display image logo true/false.\n  src: img/logo.png        ## `.svg` and `.png` are recommended,please put image into the theme folder `/jacman/source/img`.\nfavicon: img/favicon.ico   ## size:32px*32px,`.ico` is recommended,please put image into the theme folder `/jacman/source/img`.     \napple_icon: img/jacman.jpg ## size:114px*114px,please put image into the theme folder `/jacman/source/img`.\nauthor_img: img/author.jpg ## size:220px*220px.display author avatar picture.if don\'t want to display,please don\'t set this.\n\n#### index post is expanding or not \nindex:\n  expand: true           ## default is unexpanding,so you can only see the short description of each post.\n  excerpt_link: Read More  \n  \n#### Author information\nauthor:\n  intro_line1:  "Hello, I am Butcher.”\n  intro_line2:  “Welcome to my blog, enjoy it.”\n  weibo:      ## e.g. wuchong1014 or 2176287895 for http://weibo.com/2176287895\n  weibo_verifier:  ## e.g. b3593ceb Your weibo-show widget verifier ,if you use weibo-show it is needed.\n  tsina:      ## e.g. 2176287895  Your weibo ID,It will be used in share button.\n  douban:     ## e.g. wuchong1014 or your id for https://www.douban.com/people/wuchong1014\n  zhihu:      ## e.g. jark  for http://www.zhihu.com/people/jark\n  email:      tufu9441@gmail.com ## e.g. imjark@gmail.com\n  twitter:    homyung ## e.g. jarkwu for https://twitter.com/jarkwu\n  github:     tufu9441 ## e.g. wuchong for https://github.com/wuchong\n  facebook:   ## e.g. imjark for https://facebook.com/imjark\n  linkedin:   ## e.g. wuchong1014 for https://www.linkedin.com/in/wuchong1014\n  google_plus:    ## e.g. "111190881341800841449" for https://plus.google.com/u/0/111190881341800841449, the "" is needed!\n  stackoverflow:  ## e.g. 3222790 for http://stackoverflow.com/users/3222790/jark\n## if you set them, the corresponding  share button will show on the footer\n\n#### Toc\ntoc:\n  article: false   ## show contents in article.\n  aside: false     ## show contents in aside.\n## you can set both of the value to true of neither of them.\n## if you don\'t want display contents in a specified post,you can modify `front-matter` and add `toc: false`.\n\n#### Links\nlinks:\n  冲田杏梨: http://anri-okita.tumblr.com\n  羽中漫步: http://www.jzwalk.com\n  灰常记忆: http://bestcherish.com\n  怡红院落: http://imnerd.org\n  生活志: http://louishan.com\n  浩子: http://haozer.com\n  雅岚文艺博客: http://www.yalanbooks.net\n  Sloger\'s Blog: http://blog.sloger.info\n\n  \n\n#### Comment\nduoshuo_shortname: ## e.g. wuchong   your duoshuo short name.\ndisqus_shortname:  ## e.g. wuchong   your disqus short name.\n\n#### Share button\njiathis:\n  enable: false ## if you use jiathis as your share tool,the built-in share tool won\'t be display.\n  id:    ## e.g. 1889330 your jiathis ID. \n  tsina: ## e.g. 2176287895 Your weibo id,It will be used in share button.\n  \n#### Analytics\ngoogle_analytics:\n  enable: false\n  id:        ## e.g. UA-46321946-2 your google analytics ID.\n  site:      ## e.g. wuchong.me your google analytics site or set the value as auto.\n## You MUST upgrade to Universal Analytics first!\n## https://developers.google.com/analytics/devguides/collection/upgrade/?hl=zh_CN\nbaidu_tongji:\n  enable: false\n  sitecode:  ## e.g. e6d1f421bbc9962127a50488f9ed37d1 your baidu tongji site code\ncnzz_tongji:\n  enable: false\n  siteid:    ## e.g. 1253575964 your cnzz tongji site id\n\n#### Miscellaneous\nShowCustomFont: true  ## you can change custom font in `variable.styl` and `font.styl` which in the theme folder `/jacman/source/css`.\nfancybox: true        ## if you use gallery post or want use fancybox please set the value to true.\ntotop: true           ## if you want to scroll to top in every post set the value to true\n\n\n#### Custom Search\ngoogle_cse: \n  enable: false\n  cx:   ## e.g. 018294693190868310296:abnhpuysycw your Custom Search ID.\n## https://www.google.com/cse/ \n## To enable the custom search You must create a "search" folder in \'/source\' and a "index.md" file\n## set the \'front-matter\' as\n## layout: search \n## title: search\n## ---\nbaidu_search:     ## http://zn.baidu.com/\n  enable: false\n  id:   ## e.g. "783281470518440642"  for your baidu search id\n  site: http://zhannei.baidu.com/cse/search  ## your can change to your site instead of the default site\n\u0000',
     position: 1292,
     line: 41,
     column: 2 },
  message: 'Process failed: _config.yml',
  domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object] ] },
  domainThrown: true,
  stack: undefined }

经过反复试验，我确定只要修改了这里就会出现这种状况，把那两句话恢复原状后回到正常。

**Comment by wuchong** [comment]
貌似你用了中文的双引号？  用英文的双引号 ""

**Comment by tufu9441** [comment]
应该不会啊，我就是在原来的基础上直接修改文字，都没动引号。On 周六, 1月 17, 2015 at 10:12,  wuchong/jacman <reply@reply.github.com> wrote:            貌似你用了中文的双引号？  用英文的双引号 ""

**Comment by wuchong** [comment]
把你的配置文件贴出来看看？

发自我的 iPhone
