### ISSUE TITLE
首页不显示每一篇文章的评论数量

### ISSUE THREAD

**Issue by tufu9441** [wuchong/jacman#23]
我的首页每一篇文章下面都显示“暂无评论”，或者连“暂无评论”四个字都没有，只有那个灰色的评论小图标，但是实际上每一篇文章进去以后都是有多说评论的，不知道该如何解决？我的网站是http://haomwei.com

**Comment by tufu9441** [comment]
我知道原因了，是我从typecho转过来的时候多说里面thread_key对应不上，目前自己还没搞定……

**Comment by wuchong** [comment]
嗯，我看你现在是正常显示了

**Comment by tufu9441** [comment]
呃……一直也没有正常过啊。由于我是从typecho转过来的，我试了几个工具把typecho的评论导入多说的时候生成的thread_key都是文章的cid数字，但是在hexo下根本找不到一个类似的字段与之对应，所以就一直对不上，评论也就显示不出来，我不得已把comment.ejs下面data-thread-key="<%- page.path %>”这一段给删除了，这样在文章页面中只要url能与之前对应上，评论就能显示了。但是在需要显示评论数量的地方必须还是要参照thread_key，而且之前我有个留言板上的评论也一直显示不出来，也是这个蛋疼的thread_key的原因。

**Comment by wuchong** [comment]
嗯，因为多说的设计，要获取评论数量就必须使用 thread_key ，目前 Jacman 是采用 uri 来作为 thread_key ， 无法获取你自己定义的 cid 。 你可以试试通过 多说控制台修改文章的 thread_key ，如下图。

![image](https://cloud.githubusercontent.com/assets/5378924/5795530/a533de6e-9fcc-11e4-8184-7ec1e833969b.png)
