### ISSUE TITLE
comment插件不显示

### ISSUE THREAD

**Issue by summernone** [wuchong/jacman#26]
在pc上评论不显示 但是在pad和iphone上可以显示 目录也是这样 这是什么问题

**Comment by wuchong** [comment]
是不是网络问题？  有时候网络不好，多说评论就会加载不出来。

**Comment by summernone** [comment]
我不懂网站开发，只是iphone很容易就出来了，看你的博客也是一下子就出来了，用chrome看了下html的源码，发现是有duoshuo的代码的，不知道什么问题，有啥好的建议吗

**Comment by wuchong** [comment]
能给下你网站的网址吗？

**Comment by wuchong** [comment]
最近多说的服务部太稳定。
