### ISSUE TITLE
本地编辑好的markdown内容，网页上显示的列表内容有问题。

### ISSUE THREAD

**Issue by DragonLayout** [wuchong/jacman#30]
比如
1.first
   - one
    1. one
在网页上，有序列表里嵌套的无序列表显示会出现问题，变成有序列表。

**Comment by wuchong** [comment]
![image](https://cloud.githubusercontent.com/assets/5378924/6747689/e79b1a36-cf17-11e4-9714-dfe86867b855.png)

有序列表里嵌套无序列表，没有问题呀，仍然是无序列表啊。 

使用有序列表 OR 无序列表，取决于你使用 `1.` 还是 `- `
