### ISSUE TITLE
代码高亮是要再自已添加吗？

### ISSUE THREAD

**Issue by ada87** [wuchong/jacman#31]
我下载了此主题生成站点后，算是正常，但所有的代码块都是白底黑字没有样式。看DEMO的代码块是黑底彩字很漂亮，这个是要自己额外添加高亮模块吗？

**Comment by wuchong** [comment]
```
```java
...
```

要代码高亮，使用这种语法。更多的请阅读 markdown语法 https://guides.github.com/features/mastering-markdown/

**Comment by jijiaxin** [comment]
这个是配置default和night两种代码快风格，配置night就好了
