### ISSUE TITLE
hexo 3.0使用不了主题

### ISSUE THREAD

**Issue by zhiyue** [wuchong/jacman#33]
使用 hexo g 后

![](https://camo.githubusercontent.com/f8802c509f357c4c899613b9771f4fb11cf5b7d7/687474703a2f2f7777342e73696e61696d672e636e2f6c617267652f38643665326433386777316571316d7775777261766a323068723063733736342e6a7067)

**Comment by wuchong** [comment]
是的，Jacmam 目前还不支持3.0

可以降级到 2.8.3  使用 https://coderq.com/t/hexojiang-ji-3-dot-0-to-2-dot-8/1851

**Comment by wuchong** [comment]
Now jacman is available for Hexo 3.0
