### ISSUE TITLE
有没有办法添加对分类和标签的编辑功能，标签下文章较多时如何修改标签名称？

### ISSUE THREAD

**Issue by Eurry** [wuchong/jacman#34]
假如一个标签“Java”下有50个文章，现在想对这50篇文章进行再分类，这里需要对标签“Java”重命名，还需要移动文章到新建的标签下。
有什么方便的办法么，除了依次对这50个文章的md文件进行修改。

**Comment by wuchong** [comment]
目前是只能手工进行再分类，因为Hexo是个静态博客，不能像wordpress那样动态修改。。 

当然也可以看看有没有提供这种修改功能的插件，据我所知目前还没有...
