### ISSUE TITLE
首页无法显示公式

### ISSUE THREAD

**Issue by chenyou-fdu** [wuchong/jacman#37]
在首页中，文章中的mathjax公式都显示不出来，请问是我设置不对么还是什么原因呢。

**Comment by wuchong** [comment]
Thanks  我会尽快出一个fix

**Comment by wuchong** [comment]
最新版本在配置文件中加了个配置项 `mathjax: true` , 可以全局启用 mathjax

**Comment by chenyou-fdu** [comment]
已更新，挺好的，辛苦！

**Comment by devinbai** [comment]
遇到在本地可以渲染出公式，但是部署到github上公式就显示不出来，楼主有遇到吗？
