### ISSUE TITLE
增加设置 版权声明

### ISSUE THREAD

**Issue by dujnan** [wuchong/jacman#38]
能否在配置文件中增加一个 版权声明 的部分？类似[设置 Creative Commons 协议](https://github.com/iissnan/hexo-theme-next/wiki/%E8%AE%BE%E7%BD%AE-Creative-Commons-%E5%8D%8F%E8%AE%AE)

**Comment by wuchong** [comment]
可以考虑添加一个，多谢建议。

**Comment by wuchong** [comment]
暂时决定添加在页脚底部 @ 2015 <yourname> 的右边。

![image](https://cloud.githubusercontent.com/assets/5378924/6915521/48978a88-d7c7-11e4-904c-52d0714cd0c8.png)

**Comment by luoxiaohei** [comment]
博主发现一个问题，现在增加的版权声明只有在首页才会显示为图片，在文章内就变成了Creative Commons，不知道是否是有意为之的。另外当评论数很多时，版权声明并不能很明显的展示出来。可否做成在md文件内声明，然后如同解析分类一样进行解析版权声明，如果有的话就展示在分类的左侧。

**Comment by wuchong** [comment]
分类的左侧 的位置不是很清楚，你是指哪里？

**Comment by luoxiaohei** [comment]
就是在文章最下边，如果在md文件里声明了分类和标签，在文章末尾，分享选项的左边会有显示分类和标签，我想如果可以享声明分类和标签一样，在md文件里进行版权信息的声明，这样可以有更好的控制性。
![](http://ww2.sinaimg.cn/large/68ddd7e3jw1eqpanquzj9j20ws01qwek.jpg)

**Comment by wuchong** [comment]
你的意思是，可能不同的文章会发布成不同的CC版权？

**Comment by luoxiaohei** [comment]
是的，如果可以做这样的控制是最好的。

**Comment by wuchong** [comment]
多谢你的意见。

我先将你说到的 CC 图片不显示的问题修复了。  CC的摆放位置再听听大家的意见。

**Comment by luoxiaohei** [comment]
好的，辛苦博主了，O(∩_∩)O
