### ISSUE TITLE
首页是自动生成的还是自己手写？

### ISSUE THREAD

**Issue by lyjamare** [wuchong/jacman#39]
gh-pages中的index.html是怎么生成的

我的只能进入每个文章，文章的url都是日期+题目那种
我知道首页对应的是index.html,这个是得自己手写吗？

**Comment by lyjamare** [comment]
我的输入localhost:4000/
显示cannot get /

**Comment by wuchong** [comment]
自动生成的，由主题定义的。 

是否是因为你定义的 root 不是   /   ？

**Comment by lyjamare** [comment]
我的hexo g
没有下面这句
[create] Public: index.html

**Comment by lyjamare** [comment]
解决了

**Comment by wuchong** [comment]
是什么原因呢？

**Comment by yinrongping** [comment]
我也遇到这个问题，咱解决的呢？
