### ISSUE TITLE
网站统计的设计不太优雅

### ISSUE THREAD

**Issue by flyhigher139** [wuchong/jacman#43]
能够重新设计一下网站统计在页面中的显示？

比如，把网站统计与footer合并

**Comment by wuchong** [comment]
目前网站统计是不显示的。你的意思是  希望网站统计的图表能显示出来，放在footer里？

**Comment by flyhigher139** [comment]
如果不显示网站统计那是最好的

但我这边添加百度和cnzz的统计后，会在最下面很不优雅的显示这两个东西
我使用chrome浏览器（版本 41.0.2272.101）

添加百度统计：
![alt 统计1](http://7tsygu.com1.z0.glb.clouddn.com/github1.png)

添加百度和cnzz两个统计：
![alt 统计2](http://7tsygu.com1.z0.glb.clouddn.com/github2.png)

**Comment by wuchong** [comment]
哦，百度统计的图表，我记得在百度统计控制台里是可以控制它是否显示的。

不过多谢你的提醒，我会在主题中默认将这些图表隐藏

**Comment by flyhigher139** [comment]
好的～ 辛苦！

**Comment by wuchong** [comment]
```
<a href="http://tongji.baidu.com/hm-web/welcome/ico?s=e6d1f421bbc9962127a50488f9ed37d1" target="_blank"><img border="0" src="http://eiv.baidu.com/hmt/icon/21.gif" width="20" height="20"></a>
```
百度统计的插入图标是这样的。 没有class，目前还不知道怎么将这个图标隐藏 。 :(

**Comment by wuchong** [comment]
如果要隐藏百度统计的图标，可以进入百度统计的管理页面，关闭显示图标

**Comment by flyhigher139** [comment]
OK

辛苦～

**Comment by hunkshi** [comment]
打开cnzz统计会在页面最底部显示“站长统计”四个字，cnzz管理平台貌似也没有隐藏的设置，请问如何隐藏掉这四个字？
