### ISSUE TITLE
请问如何在页面底部加上网站备案号呢

### ISSUE THREAD

**Issue by Eurry** [wuchong/jacman#46]
请问如何在页面底部加上网站备案号呢，以正常小字体显示，带链接到备案查询网站

**Comment by wuchong** [comment]
可以修改 `layout/_partial/footer.ejs`

**Comment by Eurry** [comment]
布局和字体不会改，我太笨了=。=！

**Comment by Eurry** [comment]
加上了
http://www.eurry.net/
底部就是，不过数字字体不知道怎么改

**Comment by wuchong** [comment]
你可以参考最新版本中的 `cc-license` 的写法。
