### ISSUE TITLE
Jacman对Google+的解析问题

### ISSUE THREAD

**Issue by PhiloSky** [wuchong/jacman#47]
就以我的为例
设置了g+的ID之后，文章的“作者链接”点进去就是g+的页面，但是很奇怪我的显示的是404
（1）https://plus.google.com/115880271286802330000?rel=author?rel=author
但是这个链接是可以正常访问的
（2）https://plus.google.com/115880271286802328613/posts
而wuchong你的作者链接，也是（1）这么显示的，但是点击之后会跳转到（2），所以可以正常访问
不知道是我的问题还是怎么回事

另外，觉得这种设置不是很合理，还是改成访问about页面最好
跟页面底部的作者那个链接一致，想看g+的可以直接访问页面底部的g+图标

很抱歉我不会改代码，只好提提建议了

**Comment by wuchong** [comment]
如果没有设置G+，就会默认链接到about页面。如果设置了G+，就会显示G+的链接，为的是让谷歌收集作者信息，我尝试过只在底部的G+按钮处设置链接，但是没有效果。

你的问题是G+帐号的id没有用双引号括起来。

**Comment by PhiloSky** [comment]
收到！
