### ISSUE TITLE
代码高亮异常

### ISSUE THREAD

**Issue by zhiyue** [wuchong/jacman#54]
![](http://ww3.sinaimg.cn/large/8d6e2d38gw1esr435b8fdj20qv0abq44.jpg)

**Comment by zhiyue** [comment]
http://printf.me/2015/05/19/Monty-Hall-problem/

**Comment by wuchong** [comment]
好了吗？

**Comment by zhiyue** [comment]
好了，要在站点的_config.yml 里面设置
highlight :
      auto_detect: true
