### ISSUE TITLE
关于Fenced code blocks 与 indented code blocks风格的建议

### ISSUE THREAD

**Issue by heessf** [wuchong/jacman#58]
在文章中使用这两种风格的代码块，代码块的背景等这些显示都不同，而且相差特别大，举个例子缩进代码块是灰色背景，而围栏代码块即\```围着的代码块，背景是纯黑的，建议统一一下，。

在这里写就是统一的

Fenced code blocks：使用\```
```cpp
class TextQuery {
plubic:
	using LineNo = vector<string>::size_type;
	TextQuery(std::ifstream &);
	QueryResult query(const string&) const;
private:
	shared_ptr<vector<string>> input;
	std::map<string, shared_ptr<std::set<LineNo>> result;
};
```
Indented code blocks：使用缩进

    class TextQuery {
    plubic:
	    using LineNo = vector<string>::size_type;
	    TextQuery(std::ifstream &);
	    QueryResult query(const string&) const;
    private:
	    shared_ptr<vector<string>> input;
	    std::map<string, shared_ptr<std::set<LineNo>> result;
    };

**Comment by wuchong** [comment]
嗯，多谢建议。  准备统一 faced 和 indented。 
另外新加一种灰色的 highlight 样式。
