### ISSUE TITLE
我想问一下为什么我用jacman主题的回到顶部按扭出不来呢

### ISSUE THREAD

**Issue by fin618** [wuchong/jacman#59]
按照jacman介绍的安装使用，发现totop图片都放在文件夹内，就是出不来效果，没有图片在网站显示，求解决，谢谢！

**Comment by heessf** [comment]
主题的配置文件里有开启选项，默认是开启的，看看你是不是删了

**Comment by fin618** [comment]
totop: true           ## if you want to scroll to top in every post set the value to true
这个选项是这样的，然而情况是：可以在相应位置点击回到顶部，有这个效果，但是出不来图片，不明原因。

**Comment by ge-ce** [comment]
我的也是，根本没有那个图标，没法回到顶部。。。

**Comment by wuchong** [comment]
你们的域名是多少 ？

**Comment by fin618** [comment]
我换了kael的主题，但是找到两个用jacman这个主题也出现这个问题的
[More and More](http://aeesky.github.io/) 和 [Peng的博客](http://chenpengdsp.com/)

**Comment by wuchong** [comment]
你给的这两个博客都是正常的呀。  都能看到返回顶部的图片。

看不到图片的是因为页面长度还不够，需要>1000才会显示。

**Comment by ge-ce** [comment]
我的是电脑网页有，手机网页上就没有。。
我看到有些主题的手机页面也是有的，不知道这个是怎么回事？

**Comment by wuchong** [comment]
哦   手机端的返回顶部我特意隐藏掉了。  因为在ios上是可以点击顶部直接返回的。  Android上不清楚是否有这个功能。

**Comment by ge-ce** [comment]
很明显，Android不可以，因为安卓没有顶部那一栏。。

**Comment by wuchong** [comment]
安卓也有顶部状态栏的，只是可能没有返回顶部的功能。

**Comment by fin618** [comment]
哦 原来是这样啊，那能不能修改>1000这个参数呢？
