### ISSUE TITLE
怎么临时取消代码块的行号？

### ISSUE THREAD

**Issue by ge-ce** [wuchong/jacman#63]
在一篇文章中，代码块默认有行号，想要让某些代码块没有行号，要怎么做？
`indented code blocks` 可以是没有行号的，但是跟 `fenced code blocks` 的颜色是不一样的，我希望看起来都是相同的样式～～

**Comment by wuchong** [comment]
在根目录配置文件中设置
```
highlight: #代码高亮
  enable: true #是否启用
  line_number: false #是否显示行号
```

**Comment by ge-ce** [comment]
我是想一篇文章中有的代码块有行号，有的没有。。。配置文件里设置是针对一整篇文章的。

**Comment by wuchong** [comment]
那你可以用 indented code blocks 。
刚更新的最新版本，indented code blocks 的样式与 fenced code blocks 一致了

**Comment by ge-ce** [comment]
嗯，试了一下可以了~~
但是我又发现另外一个问题，这样一来所有文章的代码要么是白色，要么是黑色。
最好可以在每篇文章内单独设置，就像那个目录的 `list_number` 一样。
