### ISSUE TITLE
关于博客分享的问题

### ISSUE THREAD

**Issue by xiamenwcy** [wuchong/jacman#64]
我这些天也使用了jacman主题搭建博客，但是发现写的博客虽然有分享功能，但是不能链接到正确的网页。比如扫微信使用手机访问时就会出现404页面。不知怎么修复。我的博客为http://xiamenwcy.github.io/

**Comment by wuchong** [comment]
我这用微信扫一扫   是能正确打开网页的

**Comment by xiamenwcy** [comment]
问题解决了。谢谢啊
