### ISSUE TITLE
关于百度统计小图标和不蒜子显示单页面访问量的位置设置问题

### ISSUE THREAD

**Issue by xiamenwcy** [wuchong/jacman#67]
您好，我按照Jacman指南添加了百度统计功能，但是发现百度统计的小图标填写到了网站的底部，如图：
![][1]
我想将小图标填到其它位置，比如：
![][2]
我不知道该怎么设置，是否应该在themes/你的主题/layout/_partial/footer.ejs添加呢？那怎么添加呢？
还有一个问题是：
我想添加不蒜子的单页面访问量到每篇文章的开头，比如：
![][3]
但是不知道该添加到哪个ejs中，还有具体怎么添加？
以上问题最好可以给一个模板或者发个截图过来。十分感谢啊！！

  [1]: https://dn-xiamenwcy.qbox.me/busuanzi/wo.jpg
  [2]: https://dn-xiamenwcy.qbox.me/busuanzi/your.jpg
  [3]: https://dn-xiamenwcy.qbox.me/busuanzi/he.jpg

**Comment by wuchong** [comment]
1. 百度统计图标换位置，改动 `analytics.ejs`和`footer.ejs`两个文件
![image](https://cloud.githubusercontent.com/assets/5378924/8469641/b666a152-20b0-11e5-9246-aea879cd2096.png)

![image](https://cloud.githubusercontent.com/assets/5378924/8469652/ce85cdd0-20b0-11e5-8bb7-638d5dc72b87.png)

2. 添加不蒜子，在`header.ejs`中如图位置添加，注意要修改样式
![image](https://cloud.githubusercontent.com/assets/5378924/8469670/3ad4c2e8-20b1-11e5-8d82-230aaf2e1282.png)
