### ISSUE TITLE
文章右上角出现　 “发表于 2015-07-21　By [object Object]”

### ISSUE THREAD

**Issue by starqiu** [wuchong/jacman#74]
您好！
我的文章右上角总是出现　 “发表于 2015-07-21　By [object Object]”

在fontmatter中添加author属性也没有用，请问这是什么原因呢？用其他主题没有这个问题呢。

另外，博客主题中有一些繁体字，比如链接。

烦请拨冗回复，谢谢！

**Comment by wuchong** [comment]
主题配置文件中的 author 没填？

**Comment by AzenHuang** [comment]
我的也出现一样的问题，这是怎么回事？
![image](https://cloud.githubusercontent.com/assets/5846900/8816842/89fcea0a-305e-11e5-9a4e-332d3b456931.png)

**Comment by starqiu** [comment]
@wuchong 您好！根目录配置文件中的 author 填了的,
![jcman_config](https://cloud.githubusercontent.com/assets/3734690/8844787/885e8a44-314b-11e5-8d0f-c239106be399.png)

**Comment by starqiu** [comment]
@wuchong 您好！根目录配置文件中的 author 填了的,
![Uploading jcman_config.png…]()

**Comment by starqiu** [comment]
@wuchong 您好！根目录配置文件中的 author 填了的,
![jcman_config](https://cloud.githubusercontent.com/assets/3734690/8844835/358b1e8a-314c-11e5-87f2-6b55696b48c3.png)

**Comment by starqiu** [comment]
找到原因了，是主题的根目录下配置文件没填author，我只填了博客根目录下的author。
