### ISSUE TITLE
用最新的hexo和jacman发现诸多问题

### ISSUE THREAD

**Issue by AzenHuang** [wuchong/jacman#76]
感谢提供这么好的主题！
我之前使用旧版的hexo的时候没有出现问题，现在用新版的出现如下问题，

豆瓣、知乎、微博、标签云等插件不显示，多说评论不显示，文章作者显示成[object Object]。
具体参见：https://azenhuang.github.io
配置文件：https://github.com/AzenHuang/AzenHuang.github.io/blob/master/_config.yml

**Comment by wuchong** [comment]
1. `author.douban`填的是豆瓣id，不是url。  比如`https://www.douban.com/people/wuchong1014`只需要填`wuchong1014`
2. 你使用的 hexo 具体版本号是多少 ？

**Comment by AzenHuang** [comment]
hexo-cli: 0.1.7
os: Windows_NT 6.1.7601 win32 x64
http_parser: 2.3
node: 0.12.7
v8: 3.28.71.19
uv: 1.6.1
zlib: 1.2.8
modules: 14
openssl: 1.0.1p

**Comment by AzenHuang** [comment]
把你的site分支下载到本地，生成博客时出错
![image](https://cloud.githubusercontent.com/assets/5846900/8842426/ad70da7c-312c-11e5-9c8b-9d26c36de9c1.png)

**Comment by AzenHuang** [comment]
配置文件修改应该在主题下，我在根目录修改导致错了
