### ISSUE TITLE
tags更改后，显示0

### ISSUE THREAD

**Issue by mBigFlower** [wuchong/jacman#84]
我点击menu的tags想看下tag分类，我发现了我之前更换过的tag，本来以前的tag已经没有了 但是这里显示了tag的右上角数量是0

加入了评论功能后，暂无评论四个字不显示出来

**Comment by mBigFlower** [comment]
图片上传不上来，，， 
暂无评论四个字那个问题，我是知道需要一点时间的 不过有的时候还是不出现这四个字

**Comment by mBigFlower** [comment]
www.flowerfat.com
没法给你看图片，
你可以去我的blog看下哈。我在那里置顶了个帖子上传了错误情况的图片

**Comment by wuchong** [comment]
1. tag的问题，你需要hexo clean 之后再 hexo deploy 或者 hexo server   就可以了。
2. 四个字显示不出来的问题，这个跟多说服务有关系，多说服务器太烂了，经常显示不出来。

**Comment by mBigFlower** [comment]
感谢哈~ 
楼主打魔兽不？有没有人说你这个头像很像820啊

**Comment by mBigFlower** [comment]
当然我说的是小图

**Comment by wuchong** [comment]
嗯，有人说过。 
这楼歪到dota去了...
