### ISSUE TITLE
Archive 页面如何自定义数目？

### ISSUE THREAD

**Issue by wangyufeng0615** [wuchong/jacman#89]
默认似乎是显示五篇文章。
这样的话就得频繁地点下一页。
如何在一个页面中显示更多？

谢谢

如果要实现按照年份/月份，自动归类，需要自行修改吗？
比如这样：http://www.ruanyifeng.com/blog/essays/

**Comment by wuchong** [comment]
1. 根目录下_config.yml 中 `per_page: 20`试试
2. 是的， 需要自行修改
