### ISSUE TITLE
使用hexo server预览和hexo generate后，百度站内搜索ID不正确

### ISSUE THREAD

**Issue by kowenzhang** [wuchong/jacman#99]
在theme下_config.yml中开启百度站内搜索，正确设置了搜索ID（我的是20位），hexo server和generate后，使用chrome调试看到搜索框的隐含ID参数为 < input name="s" type="hidden" value="xxxxxxxxxxxxxxxxx000" >，后三位都变成了0， 造成站内搜索无法正常使用。

**Comment by kowenzhang** [comment]
是不是位数太长，超出了id数据类型的取值范围

**Comment by wuchong** [comment]
嗯 ， 配置的时候用双引号引起来

**Comment by kowenzhang** [comment]
好了。  刚开始用的单引号，没起作用。
